### ISSUE TITLE
Connect with Fitbit platform

### ISSUE THREAD

**Issue by wangsha** [blurrcat/xponentialy#4]
Reference:
https://github.com/orcasgit/python-fitbit
https://wiki.fitbit.com/display/API/OAuth+Authentication+in+the+Fitbit+API

**Comment by blurrcat** [comment]
The system is now able to get notifications and update activity data. But intraday activity hasn't been implemented since fitbit hasn't open it to us yet.
OAuth part will be implemented in feature/auth

**Comment by wangsha** [comment]
okay, i will deal with this
